<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit551546bd9c3439f2427df2984bb2a095
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Wof\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Wof\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'AltoRouter' => __DIR__ . '/..' . '/altorouter/altorouter/AltoRouter.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit551546bd9c3439f2427df2984bb2a095::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit551546bd9c3439f2427df2984bb2a095::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit551546bd9c3439f2427df2984bb2a095::$classMap;

        }, null, ClassLoader::class);
    }
}
